name = "update-goproxy"  # Worker 的名称，通常是你在 Cloudflare 控制面板中看到的名称
type = "javascript"  # Worker 使用的编程语言类型，通常是 'javascript' 或 'webpack' 等
main = "worker.js"

# 配置 Worker 的运行环境
[env.production]
compatibility_date = "2024-12-29"  # Worker 的兼容性日期，决定你的 Worker 脚本在哪个时间点生效

# 配置不同环境的设置，可以配置多个环境，例如 'production' 和 'staging'
[env.staging]
compatibility_date = "2024-12-29"

# API Token 的配置
[account]
# 如果需要的话，你可以指定账户 ID 和 API Token（例如通过环境变量提供）
